#spring:
#  application:
#    name: product-service2
    
server:
  port: 8081
  
spring:
#  config:
#    import: configserver:http://localhost:8888
  application:
    name: product-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   